irmasoft_home_homepage:
    path:     /
    defaults: { _controller: irmasoftHomeBundle:Default:index }

irmasoft_home_contact:
    path:     /contact
    defaults: { _controller: irmasoftHomeBundle:Default:contact }

irmasoft_home_about:
    path:     /about
    defaults: { _controller: irmasoftHomeBundle:Default:about }

irmasoft_home_services:
    path:     /services
    defaults: { _controller: irmasoftHomeBundle:Default:services }

irmasoft_home_services_web:
    path:     /services/developpement-web
    defaults: { _controller: irmasoftHomeBundle:Default:devWeb }

irmasoft_home_formations:
    path:     /services/formations
    defaults: { _controller: irmasoftHomeBundle:Default:formations }

irmasoft_home_apps_mobile:
    path:     /services/Application-Mobile
    defaults: { _controller: irmasoftHomeBundle:Default:appsMobile }
